directories:
  output: release
  buildResources: build
appId: com.pokertrainer.app
productName: Poker Trainer
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
win:
  target: nsis
  icon: assets/icon.ico
electronVersion: 27.3.11
